### ISSUE TITLE
Can't install Signal add-on

### ISSUE THREAD

**Issue by SmarterHomeLife** [haberda/hassio_addons#21]
I'm building 2 new systems, an RPi4 and an Odroid N2+, and having trouble installing the Signal add-on on both.

Running HassOS 2021.3.0b7 and Supervisor 2021.03.1

I can add the custom repository but when I try to install the Signal add-on I get the following errors;

21-03-03 05:38:01 ERROR (MainThread) [supervisor.jobs] Unhandled exception: 'NoneType' object has no attribute 'is_file'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 100, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 182, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 491, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 500, in _build
    build_env = AddonBuild(self.coresys, self.addon)
  File "/usr/src/supervisor/supervisor/addons/build.py", line 32, in __init__
    super().__init__(
  File "/usr/src/supervisor/supervisor/utils/common.py", line 59, in __init__
    self.read_data()
  File "/usr/src/supervisor/supervisor/utils/common.py", line 72, in read_data
    if self._file.is_file():
AttributeError: 'NoneType' object has no attribute 'is_file'

**Comment by haberda** [comment]
I am not sure what the problem is based on your log. I see you are on the beta channel, I suppose it's possible something in the beta is breaking it. I guess a couple things to check: do you have sufficient disk space to build the container? Unlike most add-ons this one downloads a container and builds it into the add-on on your local machine, which requires some disk space. Others are pre-built in the cloud. Also, is it possible you have permission problems?

**Comment by SmarterHomeLife** [comment]
Thanks for your reply @haberda it looks like it was something in the beta breaking it as I also couldn't update from 0.36 to 0.36.1 on my main system, all working now on 2021.3 so I'll close this.
