### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by dreem2001** [haberda/hassio_addons#33]
Hello. I'm not sure if it's not my specific issue but please let me know.
Today add-on stopped sending messages from HA without any errors in add-ons logs.
I tried to send message manually from inside of the container. It looks like the SignalLib can't reach Signal API endpoint for some reason.
The container has Internet connection.
The error:
```signal-api@1315902c-signal-messenger:/data/data$ signal-cli --config /data --verbose -u +7xxxxxxxxxx send -m "test" +7xxxxxxxxxx
2021-05-01T20:29:20.414+0300 [main] WARN LibSignal - [PhoneNumberFormatter]: Got local CC: RU
2021-05-01T20:29:20.439+0300 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-05-01T20:29:20.517+0300 [main] INFO LibSignal - [WebSocketConnection]: connect()
2021-05-01T20:29:21.085+0300 [main] WARN LibSignal - [SignalServiceMessageSender]: No attachments present...
2021-05-01T20:29:21.384+0300 [main] WARN LibSignal - [SignalServiceMessageSender]: java.io.IOException: No connection!
        at org.whispersystems.signalservice.internal.websocket.WebSocketConnection.sendRequest(WebSocketConnection.java:206)
        at org.whispersystems.signalservice.api.SignalServiceMessagePipe.send(SignalServiceMessagePipe.java:194)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:1545)
        at org.whispersystems.signalservice.api.SignalServiceMessageSender.sendMessage(SignalServiceMessageSender.java:316)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1393)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:1319)
        at org.asamk.signal.manager.Manager.sendMessage(Manager.java:982)
        at org.asamk.signal.dbus.DbusSignalImpl.sendMessage(DbusSignalImpl.java:94)
        at org.asamk.signal.commands.SendCommand.handleCommand(SendCommand.java:132)
        at org.asamk.signal.commands.DbusCommand.handleCommand(DbusCommand.java:15)
        at org.asamk.signal.App.handleLocalCommand(App.java:204)
        at org.asamk.signal.App.init(App.java:164)
        at org.asamk.signal.Main.main(Main.java:49)

2021-05-01T20:29:21.385+0300 [main] WARN LibSignal - [SignalServiceMessageSender]: [sendMessage] Pipe failed, falling back...
2021-05-01T20:29:21.488+0300 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
2021-05-01T20:29:21.488+0300 [OkHttp https://textsecure-service.whispersystems.org/...] INFO LibSignal - [WebSocketConnection]: onOpen() connected
1619890160435
2021-05-01T20:29:22.436+0300 [main] INFO LibSignal - [WebSocketConnection]: disconnect()
2021-05-01T20:29:22.442+0300 [main] INFO LibSignal - [WebSocketConnection]: disconnect()```

Do somebody has the same issue or what can I test\check to fix the issue?
Thanks!

**Comment by dreem2001** [comment]
https://github.com/AsamK/signal-cli/issues/609

**Comment by haberda** [comment]
I've been on vacation sorry for the delayed response. It seems from the other thread that you got it working again, so I will close this for now.
